### ISSUE TITLE
Turn on touchscreen in recovery

### ISSUE THREAD

**Issue by famouzkk** [A20e/android_kernel_samsung_exynos7885#1]
Hey, here is fix for not working touchscreen in TWRP or any other recovery. In __drivers/input/touchscreen/himax_83xxx/himax_platform.c__ at line 851 we need to comment these lines. 
```c
	if (hx_bootmode == 2) {
		input_err(true, &client->dev, "%s : Do not load driver due to : device entered recovery mode %d\n",
			__func__, hx_bootmode);
		return -ENODEV;
	}
````
I think u should commit this change.

**Comment by AlwaysLivid** [comment]
@xyn-dotnest Hey, look at this!

**Comment by AlwaysLivid** [comment]
@famouzkk Although I'm not sure what we're going to do with this, considering that we meant to mirror the kernel sources in order to build device trees for custom ROMs easier, this *is* actually a problem we've been dealing with for a while now.

**Comment by AlwaysLivid** [comment]
I'll look at updating the kernel sources, which are currently slightly lagging behind.

**Comment by xyn-dotnest** [comment]
@famouzkk Did you ever get TWRP to boot? If so which kernel and defconfig did you use?

**Comment by famouzkk** [comment]
Yes and im using now GSI on my a20e, here is my post on xda: https://forum.xda-developers.com/android/development/recovery-twrp-3-3-1-0-galaxy-a20e-a202f-t4101353  I used exynos7885-a20e_defconfig with some standard tweaks(i mean disable knox etc, check commits on https://github.com/prashantpaddune/universal7885), also u need to match bootloader version with kernel version and thats it.
